### ISSUE TITLE
macOS clang linker error introduced with 2016-11-23 code level 

### ISSUE THREAD

**Issue by zebuscat** [Fish-Git/hyperion#1]
Hi,
trying to compile on macOS 10.12.2 I get the following error messages.
This issue was introduced with 2016-11-23 code changes:

::
::
4 warnings generated.
  CC       trace.lo
  CC       vector.lo
  CC       vm.lo
  CC       vmd250.lo
  CC       vstore.lo
  CC       w32util.lo
  CC       xstore.lo
  CCLD     libherc.la

*** Warning: Linking the shared library libherc.la against the
*** static library decNumber/lib/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library SoftFloat/lib/libSoftFloat64.a is not portable!
ld: warning: ignoring file decNumber/lib/libdecNumber64.a, file was built for archive which is not the architecture being linked (x86_64): decNumber/lib/libdecNumber64.a
ld: warning: ignoring file SoftFloat/lib/libSoftFloat64.a, file was built for archive which is not the architecture being linked (x86_64): SoftFloat/lib/libSoftFloat64.a
Undefined symbols for architecture x86_64:
  "_decContextDefault", referenced from:
      _z900_add_dfp_ext_reg in dfp.o
      _z900_add_dfp_long_reg in dfp.o
      _z900_compare_dfp_ext_reg in dfp.o
      _z900_compare_dfp_long_reg in dfp.o
      _z900_compare_and_signal_dfp_ext_reg in dfp.o
      _z900_compare_and_signal_dfp_long_reg in dfp.o
      _z900_compare_exponent_dfp_ext_reg in dfp.o
      ...
  "_decNumberAdd", referenced from:
::
::
  "_ui64_to_f64", referenced from:
      _z900_convert_u64_to_bfp_long_reg in ieee.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libherc.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

MacBook:2016-11-23_hyperion-master$ clang -v
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 
I am using the following compile/link parameters:
CFLAGS="-O3 -D_FORTIFY_SOURCE=0" CC="gcc" ./configure --enable-optimization="-O3 -mtune=native -fomit-frame-pointer -Wunreachable-code"
make

2016-11-19 code has no problem to compile !
Any advise to get around this issue ?

cheers Dirk

**Comment by zebuscat** [comment]
Downloaded wrong fork ;-) - sorry for any inconvenience
